package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var contextCmd = &cobra.Command{
	Use:   "context [project]",
	Short: "Generate context summary for a new session",
	Long: `Generate a markdown summary of recent work on a project.
Pipe this to a file to load context into your next AI session.

Example:
  mnemo context PILAN > CONTEXT.md`,
	Run: func(cmd *cobra.Command, args []string) {
		home, _ := os.UserHomeDir()
		mnemoDir := filepath.Join(home, ".mnemo")
		
		projectFilter := ""
		if len(args) > 0 {
			projectFilter = strings.ToLower(args[0])
		}
		
		// Load Claude index
		indexPath := filepath.Join(mnemoDir, "claude-index.json")
		if !pathExists(indexPath) {
			fmt.Fprintln(os.Stderr, "No index found. Run 'mnemo index' first.")
			return
		}
		
		data, _ := os.ReadFile(indexPath)
		var index []map[string]interface{}
		json.Unmarshal(data, &index)
		
		// Filter and collect relevant sessions
		var relevant []map[string]interface{}
		for _, entry := range index {
			project := entry["project"].(string)
			if projectFilter != "" && !strings.Contains(strings.ToLower(project), projectFilter) {
				continue
			}
			relevant = append(relevant, entry)
		}
		
		if len(relevant) == 0 {
			fmt.Fprintln(os.Stderr, "No matching sessions found.")
			return
		}
		
		// Generate markdown context
		fmt.Println("# Session Context")
		fmt.Println()
		fmt.Printf("Generated by mnemo on %s\n", time.Now().Format("2006-01-02 15:04"))
		fmt.Println()
		
		if projectFilter != "" {
			fmt.Printf("## Project: %s\n\n", projectFilter)
		}
		
		fmt.Printf("Found %d relevant sessions.\n\n", len(relevant))
		
		fmt.Println("## Recent Work")
		fmt.Println()
		
		for i, entry := range relevant {
			if i >= 10 {
				break
			}
			
			project := entry["project"].(string)
			messages := int(entry["messages"].(float64))
			firstQuery := ""
			if fq, ok := entry["firstQuery"].(string); ok {
				firstQuery = fq
			}
			
			fmt.Printf("### %s\n", project)
			fmt.Printf("- Messages: %d\n", messages)
			if firstQuery != "" {
				fmt.Printf("- Initial query: %s\n", truncate(firstQuery, 200))
			}
			fmt.Println()
		}
		
		fmt.Println("---")
		fmt.Println("*Use this context to continue your work.*")
	},
}

func init() {
	rootCmd.AddCommand(contextCmd)
}
