package cmd

// context.go generates a markdown summary of recent work on a project.
// Output is designed to be piped into a file and loaded into a new AI session:
//
//   mnemo context PILAN > CONTEXT.md

import (
	"fmt"
	"strings"
	"time"

	"github.com/Pilan-AI/mnemo/internal/db"
	"github.com/spf13/cobra"
)

var contextCmd = &cobra.Command{
	Use:   "context [project]",
	Short: "Generate context summary for a new session",
	Long: `Generate a markdown summary of recent work on a project.
Pipe this to a file to load context into your next AI session.

Example:
  mnemo context PILAN > CONTEXT.md`,
	Run: func(cmd *cobra.Command, args []string) {
		projectFilter := ""
		if len(args) > 0 {
			projectFilter = strings.ToLower(args[0])
		}

		if err := db.InitDB(); err != nil {
			fmt.Printf("Error opening database: %v\n", err)
			fmt.Println("Run 'mnemo index' first to build the search index.")
			return
		}
		defer db.CloseDB()

		sessions, err := db.GetRecentSessions(50)
		if err != nil {
			fmt.Printf("Error fetching sessions: %v\n", err)
			return
		}

		// Filter by project if specified
		var relevant []db.RecentSession
		for _, s := range sessions {
			if projectFilter != "" && !strings.Contains(strings.ToLower(s.Project), projectFilter) {
				continue
			}
			relevant = append(relevant, s)
		}

		if len(relevant) == 0 {
			fmt.Println("No matching sessions found.")
			if projectFilter != "" {
				fmt.Printf("No sessions match project filter '%s'.\n", projectFilter)
			}
			return
		}

		// Generate markdown context
		fmt.Println("# Session Context")
		fmt.Println()
		fmt.Printf("Generated by mnemo on %s\n", time.Now().Format("2006-01-02 15:04"))
		fmt.Println()

		if projectFilter != "" {
			fmt.Printf("## Project: %s\n\n", projectFilter)
		}

		fmt.Printf("Found %d relevant sessions.\n\n", len(relevant))

		fmt.Println("## Recent Work")
		fmt.Println()

		for i, entry := range relevant {
			if i >= 10 {
				break
			}

			fmt.Printf("### %s\n", entry.Project)
			fmt.Printf("- Tool: %s\n", entry.Tool)
			fmt.Printf("- Messages: %d\n", entry.MessageCount)
			if entry.FirstQuery != "" {
				fmt.Printf("- Initial query: %s\n", truncate(entry.FirstQuery, 200))
			}
			fmt.Println()
		}

		fmt.Println("---")
		fmt.Println("*Use this context to continue your work.*")
	},
}

func init() {
	rootCmd.AddCommand(contextCmd)
}
